### ISSUE TITLE
User and group puppet doesn't exists on CentOS8

### ISSUE THREAD

**Issue by pcevela** [puppetlabs/device_manager#65]
## Describe the Bug
On CentOS 8 user and group "puppet" are not created during installation of puppet-agent. Therefore device manager's attempts to change directories owner and groups are failing with error message and dependencies are not met.
Cron configuration is OK.

## Expected Behavior
Device manager should detect user which is running puppet-agent and change directory owners accordingly.

## Steps to Reproduce
1. Puppet master is not collocated on same server as agent.
2. Install puppet-agent from official repository (yum.puppetlabs.com)
3. Create appropriate configuration and run puppet agent -t
4. You should see similar errors:

```
puppet-agent[3714]: Applying configuration version '1573407691'
puppet-agent[3714]: Could not find user puppet
puppet-agent[3714]: (/Stage[main]/Device_manager::Conf/File[/etc/puppetlabs/puppet/devices]/owner) change from 'root' to 'puppet' failed: Could not find user puppet
puppet-agent[3714]: Could not find group puppet
puppet-agent[3714]: (/Stage[main]/Device_manager::Conf/File[/etc/puppetlabs/puppet/devices]/group) change from 'root' to 'puppet' failed: Could not find group puppet
puppet-agent[3714]: (/Stage[main]/Device_manager::Conf/File[/etc/puppetlabs/puppet/devices/nexus-1.os10.a.b.sk]) Dependency File[/etc/puppetlabs/puppet/devices] has failures: true
puppet-agent[3714]: (/Stage[main]/Device_manager::Conf/File[/etc/puppetlabs/puppet/devices/nexus-1.os10.a.b.sk]) Skipping because of failed dependencies
```

## Environment
 - puppetserver-6.7.1-1.el8
 - puppet-agent-6.10.1-1.el8
 - puppet-release-1.0.0-7.el8
 - CentOS Linux release 8.0.1905
 - Device manager 3.0.1
 - ciscopuppet 2.1.0

**Comment by DavidS** [comment]
Hi Patrik,

there are changes on master (#64 and #46) that should fix this. Would you be able try that out? 

There is now also https://github.com/puppetlabs/device_manager/blob/899b6bbab45a40a170796daaeee35cff433e029c/manifests/init.pp#L16-L17 to allow you to specify a user to run `puppet device`, rather than defaulting to root, which is not necessary.

Regards, David

**Comment by pcevela** [comment]
Hi David,
sure. Is it sufficient just to replace module files in .../modules/device manager on master or another changes have to be done (sorry for dummy question -> new to puppet :))?

**Comment by bFekete** [comment]
Having the same issue after upgrading from 6.0.5 to 6.15.0 on a RHEL7 server. I can't figure out why it's choosing the user pe-puppet.

```
Error: Could not find user pe-puppet
Error: /Stage[main]/Device_manager::Conf/File[/etc/puppetlabs/puppet/devices]/owner: change from 'root' to 'pe-puppet' failed: Could not find user pe-puppet
Error: Could not find group pe-puppet
Error: /Stage[main]/Device_manager::Conf/File[/etc/puppetlabs/puppet/devices]/group: change from 'root' to 'pe-puppet' failed: Could not find group pe-puppet
```

If you're using the class device_manager::devices, you can't override the device_manager defined type parameter because that doesn't specify the run_user and run_group when calling device_manager.
